const optionsMoedas = [
  { moeda: 'AFN', moeda_nome: 'Afegane afegão - Afeganistão', pais_nome: 'Afeganistão', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197515.png', prefixo: '؋' },
  { moeda: 'ZAR', moeda_nome: 'Rand sul-africano - África do Sul', pais_nome: 'África do Sul', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197562.png', prefixo: 'R' },
  { moeda: 'ALL', moeda_nome: 'Lek albanês - Albânia', pais_nome: 'Albânia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/3909/3909330.png', prefixo: 'L' },
  { moeda: 'EUR', moeda_nome: 'Euro - União Européia', pais_nome: 'União Européia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197615.png', prefixo: '€' },
  { moeda: 'AOA', moeda_nome: 'Kwanza angolano - Angola', pais_nome: 'Angola', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197513.png', prefixo: 'Kz' },
  { moeda: 'SAR', moeda_nome: 'Rial saudita - Árabia Saudita', pais_nome: 'Árabia Saudita', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/5111/5111777.png', prefixo: 'ر.س' },
  { moeda: 'DZD', moeda_nome: 'Dinar argelino - Argélia', pais_nome: 'Argélia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197511.png', prefixo: 'د.ج' },
  { moeda: 'ARS', moeda_nome: 'Peso argentino - Argentina', pais_nome: 'Argentina', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197573.png', prefixo: '$' },
  { moeda: 'AMD', moeda_nome: 'Dram arménio - Armênia', pais_nome: 'Armênia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197516.png', prefixo: '֏' },
  { moeda: 'AUD', moeda_nome: 'Dólar australiano - Austrália', pais_nome: 'Austrália', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/323/323367.png', prefixo: '$' },
  { moeda: 'BOB', moeda_nome: 'Boliviano - Bolívia', pais_nome: 'Bolívia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197504.png', prefixo: 'Bs.' },
  { moeda: 'BAM', moeda_nome: 'Marco convertível da Bósnia e Herzegovina - Bósnia e Herzegovina', pais_nome: 'Bósnia e Herzegovina', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/5922/5922070.png', prefixo: 'KM' },
  { moeda: 'BRL', moeda_nome: 'Real - Brasil', pais_nome: 'Brasil', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197386.png', prefixo: 'R$' },
  { moeda: 'BGN', moeda_nome: 'Lev búlgaro - Bulgária', pais_nome: 'Bulgária', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197502.png', prefixo: 'лв' },
  { moeda: 'XAF', moeda_nome: 'Franco CFA BEAC - Camarões', pais_nome: 'Camarões', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197531.png', prefixo: 'Fr' },
  { moeda: 'QAR', moeda_nome: 'Rial catarense - Catar', pais_nome: 'Catar', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197618.png', prefixo: 'ر.ق' },
  { moeda: 'CZK', moeda_nome: 'Coroa checa - República Tcheca', pais_nome: 'República Tcheca', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/5959/5959221.png', prefixo: 'Kč' },
  { moeda: 'CLP', moeda_nome: 'Pesco chileno - Chile', pais_nome: 'Chile', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197586.png', prefixo: '$' },
  { moeda: 'CNY', moeda_nome: 'Iuane chinês - China', pais_nome: 'China', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197375.png', prefixo: '¥' },
  { moeda: 'COP', moeda_nome: 'Peso colombiano - Colômbia', pais_nome: 'Colômbia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197575.png', prefixo: '$' },
  { moeda: 'KRW', moeda_nome: 'Won sul-coreano - Coréia do Sul', pais_nome: 'Coréia do Sul', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197582.png', prefixo: '₩' },
  { moeda: 'CRC', moeda_nome: 'Colón costarriquenho - Costa Rica', pais_nome: 'Costa Rica', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197506.png', prefixo: '₡' },
  { moeda: 'DKK', moeda_nome: 'Coroa dinamarquesa - Dinamarca', pais_nome: 'Dinamarca', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197565.png', prefixo: 'kr' },
  { moeda: 'EGP', moeda_nome: 'Libra egípcia - Egito', pais_nome: 'Egito', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197558.png', prefixo: 'ج.م' },
  { moeda: 'AED', moeda_nome: 'Dirame dos Emirados Árabes Unidos - Emirados Árabes Unidos', pais_nome: 'Emirados Árabes Unidos', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/323/323301.png', prefixo: 'د.إ' },
  { moeda: 'USD', moeda_nome: 'Dólar Americano - Estados Unidos', pais_nome: 'Estados Unidos', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197484.png', prefixo: '$' },
  { moeda: 'PHP', moeda_nome: 'Peso filipino - Filipinas', pais_nome: 'Filipinas', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/323/323301.png', prefixo: '₱' },
  { moeda: 'HTG', moeda_nome: 'Gurde haitiano - Haiti', pais_nome: 'Haiti', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197389.png', prefixo: 'G' },
  { moeda: 'HKD', moeda_nome: 'Dólar de Honguecongue - Honguecongue', pais_nome: 'Honguecongue', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197570.png', prefixo: '$' },
  { moeda: 'INR', moeda_nome: 'Rupia indiana - Índia', pais_nome: 'Índia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197419.png', prefixo: '₹' },
  { moeda: 'IDR', moeda_nome: 'Rupia indonésia - Indonésia', pais_nome: 'Indonésia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/323/323372.png', prefixo: 'Rp' },
  { moeda: 'IRR', moeda_nome: 'Rial iraniano - Irã', pais_nome: 'Irã', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/6211/6211416.png', prefixo: '﷼' },
  { moeda: 'IQD', moeda_nome: 'Dinar iraquiano - Iraque', pais_nome: 'Iraque', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197630.png', prefixo: 'ع.د' },
  { moeda: 'ISK', moeda_nome: 'Coroa islandesa - Islândia', pais_nome: 'Islândia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197596.png', prefixo: 'kr' },
  { moeda: 'ILS', moeda_nome: 'Novo siclo israelita - Israel', pais_nome: 'Israel', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197577.png', prefixo: '₪' },
  { moeda: 'JPY', moeda_nome: 'Iene japonês - Japão', pais_nome: 'Japão', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197604.png', prefixo: '¥' },
  { moeda: 'JOD', moeda_nome: 'Dinar jordano - Jordânia', pais_nome: 'Jordânia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/4852/4852837.png', prefixo: 'د.ا' },
  { moeda: 'LYD', moeda_nome: 'Dinar líbio - Líbia', pais_nome: 'Líbia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197411.png', prefixo: 'ل.د' },
  { moeda: 'MKD', moeda_nome: 'Dinar macedônio - Macedônia do Norte', pais_nome: 'Macedônia do Norte', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/8362/8362984.png', prefixo: 'ден' },
  { moeda: 'MGA', moeda_nome: 'Ariari malgaxe - Madagascar', pais_nome: 'Madagascar', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197383.png', prefixo: 'Ar' },
  { moeda: 'MAD', moeda_nome: 'Dirame marroquino - Marrocos', pais_nome: 'Marrocos', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197551.png', prefixo: 'د.م.' },
  { moeda: 'MXN', moeda_nome: 'Peso mexicano - México', pais_nome: 'México', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/5372/5372848.png', prefixo: '$' },
  { moeda: 'NZD', moeda_nome: 'Dólar da Nova Zelândia - Nova Zelândia', pais_nome: 'Nova Zelândia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197589.png', prefixo: '$' },
  { moeda: 'PKR', moeda_nome: 'Rupia paquistanesa - Paquistão', pais_nome: 'Paquistão', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/323/323352.png', prefixo: '₨' },
  { moeda: 'PYG', moeda_nome: 'Guarani paraguaio - Paraguai', pais_nome: 'Paraguai', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197376.png', prefixo: '₲' },
  { moeda: 'PLN', moeda_nome: 'Zlóti polaco - Polônia', pais_nome: 'Polônia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197529.png', prefixo: 'zł' },
  { moeda: 'GBP', moeda_nome: 'Libra esterlina - Reino Unido', pais_nome: 'Reino Unido', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197374.png', prefixo: '£' },
  { moeda: 'RUB', moeda_nome: 'Rublo russo - Rússia', pais_nome: 'Rússia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/4628/4628645.png', prefixo: '₽' },
  { moeda: 'XOF', moeda_nome: 'Franco CFA BCEAO - Senegal', pais_nome: 'Senegal', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197377.png', prefixo: 'Fr' },
  { moeda: 'RSD', moeda_nome: 'Dinar sérvio - Sérvia', pais_nome: 'Sérvia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197602.png', prefixo: 'дин' },
  { moeda: 'SGD', moeda_nome: 'Dólar de Singapura - Singapura', pais_nome: 'Singapura', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197496.png', prefixo: '$' },
  { moeda: 'SYP', moeda_nome: 'Libra síria - Síria', pais_nome: 'Síria', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197598.png', prefixo: 'ل.س' },
  { moeda: 'SOS', moeda_nome: 'Xelim somaliano - Somália', pais_nome: 'Somália', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197438.png', prefixo: 'Sh' },
  { moeda: 'LKR', moeda_nome: 'Rupia do Sri Lanka - Sri Lanka', pais_nome: 'Sri Lanka', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197398.png', prefixo: 'රු' },
  { moeda: 'SEK', moeda_nome: 'Coroa sueca - Suécia', pais_nome: 'Suécia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197564.png', prefixo: 'kr' },
  { moeda: 'CHF', moeda_nome: 'Franco suíço - Suíça', pais_nome: 'Suíça', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197540.png', prefixo: 'Fr' },
  { moeda: 'SRD', moeda_nome: 'Dólar surinamês - Suriname', pais_nome: 'Suriname', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197439.png', prefixo: '$' },
  { moeda: 'THB', moeda_nome: 'Baht tailandês - Tailândia', pais_nome: 'Tailândia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197452.png', prefixo: '฿' },
  { moeda: 'TWD', moeda_nome: 'Novo dólar de Taiwan - Taiwan', pais_nome: 'Taiwan', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197557.png', prefixo: '$' },
  { moeda: 'TND', moeda_nome: 'Dinar tunisino - Tunísia', pais_nome: 'Tunísia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197624.png', prefixo: 'د.ت' },
  { moeda: 'TRY', moeda_nome: 'Lira turca - Turquia', pais_nome: 'Turquia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197518.png', prefixo: '₺' },
  { moeda: 'UAH', moeda_nome: 'Grívnia ucraniana - Ucrânia', pais_nome: 'Ucrânia', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197572.png', prefixo: '₴' },
  { moeda: 'UYU', moeda_nome: 'Peso uruguaio - Uruguai', pais_nome: 'Uruguai', bandeira_img: 'https://cdn-icons-png.flaticon.com/512/197/197599.png', prefixo: '$' }
]

export {
  optionsMoedas
}
